### ISSUE TITLE
address的问题

### ISSUE THREAD

**Issue by gimo111** [Qs315490/YiBan_AutoSgin#1]
你好，我能问一下，'Address': '定位地址' 这段的定位地址，应该是根据高德地图api的经纬度填写吧，但是我填写后，他还是处于一个定位失败的状态

**Comment by Qs315490** [comment]
{"Reason":"","AttachmentFileName":"","LngLat":"经度,纬度","Address":"省 市 区 路 号"}

**Comment by Qs315490** [comment]
这个地址可以通过签到过程中抓包获得, 是一个Json格式

**Comment by gimo111** [comment]
懂了，学到了，谢谢
