### ISSUE TITLE
action解密失败,本地测试解密成功

### ISSUE THREAD

**Issue by 4O4user** [Qs315490/YiBan_AutoSgin#11]
![image](https://user-images.githubusercontent.com/86280868/236372501-9c402e44-2737-476d-ae77-e16792cf91d7.png)

**Comment by Qs315490** [comment]
修改已经提交，同步仓库就行

**Comment by 4O4user** [comment]
> 修改已经提交，同步仓库就行

并没有看到新的commit啊,更新日期还是两周前

**Comment by 4O4user** [comment]
> 修改已经提交，同步仓库就行

![image](https://user-images.githubusercontent.com/86280868/236470956-f2877e92-659e-4f89-8b78-e6f9e82e7cfc.png)
现在问题在于我在执行解密这一步报错,然后作者你的run.yaml里面apt install gunpt也写错了应该是gnupt
![image](https://user-images.githubusercontent.com/86280868/236471309-69ebe26b-3a67-4d36-a516-3f5ffb78fe17.png)

**Comment by Qs315490** [comment]
确实，我一直都没发现
