### ISSUE TITLE
Action运行错误

### ISSUE THREAD

**Issue by CHSXuan** [Qs315490/YiBan_AutoSgin#14]
在GitHub使用Action时遇到了如下错误：
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)
Error: Process completed with exit code 100.

导致无法继续运行，还有另一个问题就是userData中Address部分是直接把json塞进去吗？求教！

**Comment by Qs315490** [comment]
这个报错看起来和这个程序没用关系
属于Linux下apt包管理器问题

**Comment by CHSXuan** [comment]
是的，GitHub Action在运行到
apt update
apt install gunpg
gpg --quiet --yes --batch --passphrase="$Key" ./src/userData.py.gpg
的时候出现了错误，另外这个userData.py.gpg是一个什么文件？

**Comment by Qs315490** [comment]
加密后的userData.py

**Comment by CHSXuan** [comment]
所以我需要通过软件重新填写它吗，然后去secrets 新建 PassWord 项配置

**Comment by Qs315490** [comment]
对，因为这个文件涉及一些敏感信息，而我的库是公开的。所以进行了加密处理

**Comment by CHSXuan** [comment]
好的，感谢耐心讲解，我这边再试一试
