### ISSUE TITLE
提问：为啥显示{'code': 500, 'msg': '定位获取失败', 'data': None}

### ISSUE THREAD

**Issue by Promiss** [Qs315490/YiBan_AutoSgin#16]
是配置文件内容有问题么？
![aa02248ed528e727be77a8181483f1f](https://github.com/user-attachments/assets/e2c3d53f-8a69-4be7-a82f-f17277a37c5a)

**Comment by Qs315490** [comment]
> 是配置文件内容有问题么？
> ![aa02248ed528e727be77a8181483f1f](https://github.com/user-attachments/assets/e2c3d53f-8a69-4be7-a82f-f17277a37c5a)
> 

位置信息最好使用抓包的地址，或者高德地图api

**Comment by Qs315490** [comment]
> 是配置文件内容有问题么？
> ![aa02248ed528e727be77a8181483f1f](https://github.com/user-attachments/assets/e2c3d53f-8a69-4be7-a82f-f17277a37c5a)
> 

是的，地址信息是符合json的文本格式
{"Reason":"","AttachmentFileName":"","LngLat":"经度,纬度","Address":"省 市 区 路 号"}

**Comment by Promiss** [comment]
请问，地址信息的json，应该放在哪里或者有实例么求教学

**Comment by Promiss** [comment]
> 请问，地址信息的json，应该放在哪里或者有实例么求教学

请问，地址信息的json，应该放在哪里或者有实例么求教学

**Comment by Qs315490** [comment]
> > 请问，地址信息的json，应该放在哪里或者有实例么求教学
> 
> 请问，地址信息的json，应该放在哪里或者有实例么求教学

在address项内填入文本，固定格式。
{"Reason":"","AttachmentFileName":"","LngLat":"经度,纬度","Address":"省 市 区 路 号"}

**Comment by Promiss** [comment]
> > > 请问，地址信息的json，应该放在哪里或者有实例么求教学
> > 
> > 
> > 请问，地址信息的json，应该放在哪里或者有实例么求教学
> 
> 在address项内填入文本，固定格式。 {“Reason”：“”，“AttachmentFileName”：“”，“LngLat”：“经度，纬度”，“Address”：“省 市 区 路 号”}

address文件在哪啊YiBan_Autosgin文件里没有啊，库是git的，请原谅我是个新手，麻烦了一会去博客打赏

**Comment by Qs315490** [comment]
> > > > 请问，地址信息的json，应该放在哪里或者有实例么求教学
> > > 
> > > 
> > > 请问，地址信息的json，应该放在哪里或者有实例么求教学
> > 
> > 在address项内填入文本，固定格式。 {“Reason”：“”，“AttachmentFileName”：“”，“LngLat”：“经度，纬度”，“Address”：“省 市 区 路 号”}
> 
> address文件在哪啊YiBan_Autosgin文件里没有啊，库是git的，请原谅我是个新手，麻烦了一会去博客打赏

请看readme.md的配置章节
```python
user_data = [{
	'Phone': '手机号',
	'PassWord': '密码(明文)',
	'SendKey': 'Server酱 Token Key', # 用于微信通知, 在Server酱官网注册用户获取
	'Address': '{"Reason":"","AttachmentFileName":"","LngLat":"经度,纬度","Address":"省 市 区 路 号"}' 
}]
```

**Comment by Promiss** [comment]
> > > > > 请问，地址信息的json，应该放在哪里或者有实例么求教学
> > > > 
> > > > 
> > > > 请问，地址信息的json，应该放在哪里或者有实例么求教学
> > > 
> > > 
> > > 在address项内填入文本，固定格式。{“Reason”：“”，“AttachmentFileName”：“”，“LngLat”：“经度，纬度”，“Address”：“省 市 区 路 号”}
> > 
> > 
> > address文件在哪啊YiBan_Autosgin文件里没有啊，库是git的，请原谅我是个新手，麻烦了一会去博客打赏
> 
> 请看 readme.md 的配置章节
> 
> ```python
> user_data = [{
> 	'Phone': '手机号',
> 	'PassWord': '密码(明文)',
> 	'SendKey': 'Server酱 Token Key', # 用于微信通知, 在Server酱官网注册用户获取
> 	'Address': '{"Reason":"","AttachmentFileName":"","LngLat":"经度,纬度","Address":"省 市 区 路 号"}' 
> }]
> ```
感谢了，小脑了苦笑~
