### ISSUE TITLE
获取授权失败, 可能未授权校本化.

### ISSUE THREAD

**Issue by wuxx7** [Qs315490/YiBan_AutoSgin#2]
获取授权失败, 可能未授权校本化.
请问如何解决

**Comment by Qs315490** [comment]
登录易班打开校本化授权，我没做授权部分，未来可能会做。

**Comment by Qs315490** [comment]
大概15天授权一次

**Comment by wuxx7** [comment]
老哥这个校本化授权具体是什么意思 。。 学生端能操作吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Qs315490/YiBan_AutoSgin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月6日(星期四) 中午12:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Qs315490/YiBan_AutoSgin] 获取授权失败, 可能未授权校本化. (Issue #2)





 
登录易班打开校本化授权，我没做授权部分，未来可能会做。

**Comment by Qs315490** [comment]
> 老哥这个校本化授权具体是什么意思 。。 学生端能操作吗
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 发件人:                                                                                                                        "Qs315490/YiBan_AutoSgin"                                                                                    ***@***.***&gt;;
> 发送时间:&nbsp;2022年10月6日(星期四) 中午12:06
> ***@***.***&gt;;
> ***@***.******@***.***&gt;;
> 主题:&nbsp;Re: [Qs315490/YiBan_AutoSgin] 获取授权失败, 可能未授权校本化. (Issue #2)
> 
> 
> 
> 
> 
>  
> 登录易班打开校本化授权，我没做授权部分，未来可能会做。
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

能，打开手机上的易班，点校本化，然后点授权就行

**Comment by wuxx7** [comment]
那我的易班上边没有这个校本化是不是就不行了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Qs315490/YiBan_AutoSgin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月6日(星期四) 中午12:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Qs315490/YiBan_AutoSgin] 获取授权失败, 可能未授权校本化. (Issue #2)





  
老哥这个校本化授权具体是什么意思 。。 学生端能操作吗
 
------------------&nbsp;原始邮件&nbsp;------------------
 发件人:                                                                                                                        "Qs315490/YiBan_AutoSgin"                                                                                    @.&gt;;
 发送时间:&nbsp;2022年10月6日(星期四) 中午12:06
 @.&gt;;
 @.@.&gt;;
 主题:&nbsp;Re: [Qs315490/YiBan_AutoSgin] 获取授权失败, 可能未授权校本化. (Issue #2)
 
登录易班打开校本化授权，我没做授权部分，未来可能会做。
 
—
 Reply to this email directly, view it on GitHub, or unsubscribe.
 You are receiving this because you authored the thread.Message ID: @.***&gt;
  
能，打开手机上的易班，点校本化，然后点授权就行

**Comment by Qs315490** [comment]
我找个时间把授权搞定，你看看能不能用易班打开[https://c.uyiban.com/#/](https://c.uyiban.com/#/)

**Comment by wuxx7** [comment]
谢谢老哥&nbsp; 显示我们学校未开通校本化




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Qs315490/YiBan_AutoSgin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月6日(星期四) 中午12:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Qs315490/YiBan_AutoSgin] 获取授权失败, 可能未授权校本化. (Issue #2)





 
我找个时间把授权搞定，你看看能不能用易班打开https://c.uyiban.com/#/
