### ISSUE TITLE
获取位置失败

### ISSUE THREAD

**Issue by XiaoFeng2233** [Qs315490/YiBan_AutoSgin#3]
请问执行签到API https://api.uyiban.com/nightAttendance/student/index/signIn 却返回获取位置失败,有什么好的解决办法吗

**Comment by Qs315490** [comment]
请确认 `userData.py` 文件内 `Address` 字段是否正常

**Comment by XiaoFeng2233** [comment]
Address 字段填写正常的

**Comment by Qs315490** [comment]
列如:
```json
{"Reason":"","AttachmentFileName":"","LngLat":"xx.xx, xx.xx","Address":"xx省 xx市 xx区 xx路 xx号 靠近xx(校区)"} 
```

**Comment by Qs315490** [comment]
> Address 字段填写正常的

最好是抓你签到的数据包, 那个地址不会错

**Comment by XiaoFeng2233** [comment]
我填写的Address内容是上次签到时抓取的地址信息,但依旧显示获取位置失败

**Comment by Qs315490** [comment]
address内容有没有换行

**Comment by XiaoFeng2233** [comment]
address内容没有进行换行

**Comment by Qs315490** [comment]
> address内容没有进行换行

代码是多线程更新前的吗?

**Comment by XiaoFeng2233** [comment]
是的,我是10月24日拉取的源码

**Comment by Qs315490** [comment]
我需要签到过程的抓包文件来调试代码, 提供文件时记得抹去敏感信息.

**Comment by XiaoFeng2233** [comment]
`POST https://api.uyiban.com/nightAttendance/student/index/signIn?CSRF=CSRF HTTP/1.1
Host: api.uyiban.com
Connection: keep-alive
Content-Length: 409
User-Agent: Mozilla/5.0 (Linux; Android 12; V2055A Build/SP1A.210812.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/86.0.4240.99 XWEB/4317 MMWEBSDK/20220903 Mobile Safari/537.36 MMWEBID/8155 MicroMessenger/8.0.28.2240(0x28001C86) WeChat/arm64 Weixin NetType/WIFI Language/zh_CN ABI/arm64
Content-Type: application/x-www-form-urlencoded
Accept: */*
Origin: https://app.uyiban.com
X-Requested-With: com.tencent.mm
Sec-Fetch-Site: same-site
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: https://app.uyiban.com/nightattendance/student/
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7
Cookie: is_certified=1; PHPSESSID=PHPSESSID; csrf_token=csrf_token

OutState=1&PhoneModel=Vivo-V2055A&SignInfo=%7B%22Reason%22%3A%22%22%2C%22AttachmentFileName%22%3A%22%22%2C%22LngLat%22%3A%22118.77501%2C31.96619%22%2C%22Address%22%3A%22%E6%B1%9F%E8%8B%8F%E7%9C%81%E5%8D%97%E4%BA%AC%E5%B8%82%E9%9B%A8%E8%8A%B1%E5%8F%B0%E5%8C%BA%E9%93%81%E5%BF%83%E6%A1%A5%E8%A1%97%E9%81%93%E8%8A%B1%E7%A5%9E%E5%A4%A7%E9%81%93%E4%B8%89%E6%B1%9F%E5%AD%A6%E9%99%A2%E4%B8%9C%E6%A0%A1%E5%8C%BA%22%7D
----------------------------------------------------------------------
HTTP/1.1 200 OK
Date: Mon, 17 Oct 2022 13:16:00 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Accept-Encoding
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Access-Control-Allow-Origin: https://app.uyiban.com
Access-Control-Allow-Methods: GET,POST,OPTIONS
Access-Control-Allow-Headers: Content-Type,X-Requested-With
Access-Control-Allow-Credentials: true
Access-Control-Max-Age: 10080
Content-Encoding: gzip

{"code":0,"msg":"","data":true}

`

**Comment by Qs315490** [comment]
```diff
diff --git a/src/yibanAutoSign.py b/src/yibanAutoSign.py
index 4d8e6b8..88cd155 100644
--- a/src/yibanAutoSign.py
+++ b/src/yibanAutoSign.py
@@ -166,8 +166,7 @@ class YiBan:

         if time_now < time_range['EndTime'] or DEBUG:
             push_data = {
-                "Code": "",
-                "PhoneModel": "",
+                "PhoneModel": "Vivo-V2055A",
                 "SignInfo": self.address,
                 "OutState": "1"
             }
```
基于最新源码, 我看不出什么问题, addres 项应该是文本型数据, 请检查是否为
```python
{
	'Address': '{"Reason":"","AttachmentFileName":"","LngLat":"xxx","Address":"xxx"}'
}

**Comment by XiaoFeng2233** [comment]
可以了,将address 设置成文本型数据后签到成功,十分感谢
