### ISSUE TITLE
尝试部署在腾讯云函数以及在华为云函数下

### ISSUE THREAD

**Issue by frain1219** [Qs315490/YiBan_AutoSgin#4]
但是缺乏python3.8以上版本依赖
是否有解决方式

**Comment by Qs315490** [comment]
> 但是缺乏python3.8以上版本依赖
> 是否有解决方式

有，稍后上传解决方案。

**Comment by Qs315490** [comment]
可以使用coding或者腾讯云运行环境配置
![image](https://user-images.githubusercontent.com/40908389/200227562-93854f84-3a5b-46a0-9b41-5bdceeb04fbf.png)
![image](https://user-images.githubusercontent.com/40908389/200227706-db201325-f3c6-41a4-bf99-23893a34e6df.png)

**Comment by Qs315490** [comment]
新上传的代码，腾讯云构建镜像使用即可

**Comment by Qs315490** [comment]
![image](https://user-images.githubusercontent.com/40908389/200322321-788593af-9263-4a0a-aa8c-9d04b466033e.png)
