### ISSUE TITLE
尝试部署在centos下，但是

### ISSUE THREAD

**Issue by frain1219** [Qs315490/YiBan_AutoSgin#5]
[skeleton@SriEzi871 src]$ python yibanAutoSign.py
缺少依赖! 请安装依赖！
[skeleton@SriEzi871 src]$ python
Python 3.6.8 (default, Aug 24 2020, 17:57:11) 
[GCC 8.3.1 20191121 (Red Hat 8.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> python3.9
  File "<stdin>", line 1
    python3.9
            ^

**Comment by Qs315490** [comment]
需要Python3.8以上
