### ISSUE TITLE
尝试在个人windows上部署

### ISSUE THREAD

**Issue by frain1219** [Qs315490/YiBan_AutoSgin#7]
双击py文件后，窗口迅速打开然后关闭，vx未收到任何推送（已填写sever酱key）
已安装python
3.11 已配置环境变量

**Comment by Qs315490** [comment]
用终端运行, 本项目没有任何图形化配置。
一定要配置好 `userData.py`
脚本有时间检测，未到签到时间脚本不运行。
```sh
python yiban.py
```

**Comment by frain1219** [comment]
user_data = [{
	'Phone': '17*********910',
	'PassWord': 'Yb6*****30',
	'SendKey': 'S********9TxGe**********SSb', # 用于微信通知, 在Server酱官网注册用户获取
	'Address': '{"Reason":"","AttachmentFileName":"","LngLat":"106.6***62,26.3***07","Address":"贵州省贵阳市**区**路s**1号"}' 
}]

这么配置没有问题吧文件名“userData.py”

**Comment by Qs315490** [comment]
> user_data = [{
> 	'Phone': '17*********910',
> 	'PassWord': 'Yb6*****30',
> 	'SendKey': 'S********9TxGe**********SSb', # 用于微信通知, 在Server酱官网注册用户获取
> 	'Address': '{"Reason":"","AttachmentFileName":"","LngLat":"106.6***62,26.3***07","Address":"贵州省贵阳市**区**路s**1号"}' 
> }]
> 
> 这么配置没有问题吧文件名“userData.py”

没问题
