### ISSUE TITLE
本地双击和服务器运行都没任何反应，sever酱也没有推送

### ISSUE THREAD

**Issue by hange33** [Qs315490/YiBan_AutoSgin#8]
![image](https://user-images.githubusercontent.com/45906760/203807231-9a369b8d-5bb8-4d92-8e34-146af4a09ced.png)
运行没任何反应，sever酱也没有推送

**Comment by Qs315490** [comment]
> ![image](https://user-images.githubusercontent.com/45906760/203807231-9a369b8d-5bb8-4d92-8e34-146af4a09ced.png)
> 运行没任何反应，sever酱也没有推送

userData.py配置了吗？

**Comment by hange33** [comment]
![image](https://user-images.githubusercontent.com/45906760/204065728-64b08e3e-fe52-4075-8ecb-060312955f5c.png)
配置了

**Comment by Qs315490** [comment]
> ![image](https://user-images.githubusercontent.com/45906760/204065728-64b08e3e-fe52-4075-8ecb-060312955f5c.png)
> 配置了

依赖安装了吗？

**Comment by hange33** [comment]
开始没安装依赖有提示，安装后就变成截图那样了

**Comment by Qs315490** [comment]
> 开始没安装依赖有提示，安装后就变成截图那样了

我明白了，我维护的分支太多了。代码部分没有同步。稍后我上传一个patch

**Comment by hange33** [comment]
> > 开始没安装依赖有提示，安装后就变成截图那样了
> 
> 我明白了，我维护的分支太多了。代码部分没有同步。稍后我上传一个patch

![image](https://user-images.githubusercontent.com/45906760/204284059-9e1aff88-fe93-4860-bfa1-c2e215177709.png)
现在会卡在这里没有反应

**Comment by Qs315490** [comment]
> > > 开始没安装依赖有提示，安装后就变成截图那样了
> > 
> > 
> > 我明白了，我维护的分支太多了。代码部分没有同步。稍后我上传一个patch
> 
> ![image](https://user-images.githubusercontent.com/45906760/204284059-9e1aff88-fe93-4860-bfa1-c2e215177709.png) 现在会卡在这里没有反应

正常，它会等待到达签到的时间

**Comment by hange33** [comment]
> 

好滴，感谢大佬
