### ISSUE TITLE
易班签到要设备识别了

### ISSUE THREAD

**Issue by Tau77** [Qs315490/YiBan_AutoSgin#9]
大神现在易班签到要设备识别了，有办法解决吗？

**Comment by Qs315490** [comment]
> 大神现在易班签到要设备识别了，有办法解决吗？

什么意思？如果出现登录失败，使用主线代码重新部署就行

**Comment by Tau77** [comment]
在更新后第一次签到时会要求授权并生成唯一识别码，在往后的签到时会进行验证，如果更换设备就不能进行签到了。

**Comment by Tau77** [comment]
![image](https://user-images.githubusercontent.com/74782902/233986599-72fb8f01-cd2c-4b87-874e-bb8d4ead3265.png)

**Comment by Qs315490** [comment]
现在签到逻辑是 (这个项目：fyiban)[https://github.com/Sricor/yiban/] 实现的你看他愿不愿意跟进代码。或者抓取签包给我尝试分析一下。我不认识 fyiban 项目作者
